version: "17"

services:
  # redis: 
  #   image : redis:latest
  #   container_name: redis-bodh
  #   ports:
  #     - "6379:6379" 
  #   restart: unless-stopped


  # postgres:
  #   image: postgres:latest
  #   container_name: postgres-stack
  #   environment: 
  #     POSTGRES_USER : ${DB_USER}
  #     POSTGRES_PASSWORD : ${DB_PASSWORD}
  #     POSTGRES_DB : ${DB_NAME}
  #   ports: 
  #     - "5432:5432"
  #   volumes:
  #     # - ./server.key:/var/lib/postgresql/data/server.key
  #     # - ./server.cert:/var/lib/postgresql/data/server.crt
  #     - pg_data:/var/lib/postgresql/
  #     - ./full_backup.sql:/docker-entrypoint-initdb.d/full_backup.sql
  #     # - ./fix-perms.sh:/docker-entrypoint-initdb.d/fixPerm.sh

  #   restart: unless-stopped
  #   healthcheck: 
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d news"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  # dbmate:
  #   image: amacneil/dbmate:latest
  #   command: ["up"]   # run migrations on startup
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}  # require || disable for without ssl
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ./db:/db
  #     # - ./db/migrations:/db/migrations 

#   bodhapi: 
#     build: .
#     container_name: bodhapi-container
#     depends_on: 
#       - redis 
#       - postgres
#     ports:                  
#       - "5000:5000"
#     environment: 
#       - REDIS_URL=${REDIS_URL}
#       - DB_HOST=${DB_HOST}
#       - DB_USER=${DB_USER}
#       - DB_PASS=${DB_PASSWORD}
#       - DB_NAME=${DB_NAME}
#     command: ["node", "server.js" ]
#     restart: always
#     # volumes:
#     #   - ./server.key:/app/server.key
#     #   - ./server.cert:/app/server.cert

# volumes:
#   pg_data:


# with nginx setup with pvt network no port exposed

  bodhapi: 
    # build : . 
    image: bodhapi:0.1
    container_name: bodhapi-container

    environment: 
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_KEY: ${ACCESS_KEY}
      REFRESH_KEY: ${REFRESH_KEY}

    command: ["node", "server.js"]
    restart: always

    networks:
      - shared_private_net

networks:
  shared_private_net:
    external: true